# Generated by Django 3.0.4 on 2020-03-08 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Referee',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('half_time_goals', models.IntegerField(blank=True, null=True)),
                ('full_time_goals', models.IntegerField(blank=True, null=True)),
                ('shots', models.IntegerField(blank=True, null=True)),
                ('shots_on_target', models.IntegerField(blank=True, null=True)),
                ('shots_hit_woodwork', models.IntegerField(blank=True, null=True)),
                ('corners', models.IntegerField(blank=True, null=True)),
                ('fouls_committed', models.IntegerField(blank=True, null=True)),
                ('offsides', models.IntegerField(blank=True, null=True)),
                ('yellow_cards', models.IntegerField(blank=True, null=True)),
                ('red_cards', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('date', models.DateField()),
                ('attendance', models.IntegerField()),
                (
                    'away_team',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='away_team',
                        to='core.Team',
                    ),
                ),
                (
                    'away_team_statistics',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='away_team_statistics',
                        to='core.Statistics',
                    ),
                ),
                (
                    'local_team',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='local_team',
                        to='core.Team',
                    ),
                ),
                (
                    'local_team_statistics',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='local_team_statistics',
                        to='core.Statistics',
                    ),
                ),
                (
                    'referee',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='core.Referee'
                    ),
                ),
            ],
        ),
    ]
