# Generated by Django 3.0.4 on 2020-03-08 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(model_name='game', name='attendance',),
        migrations.RemoveField(model_name='game', name='referee',),
        migrations.AlterField(
            model_name='game',
            name='away_team_statistics',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='away_team_statistics',
                to='core.Statistics',
            ),
        ),
        migrations.AlterField(
            model_name='game',
            name='local_team_statistics',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='local_team_statistics',
                to='core.Statistics',
            ),
        ),
        migrations.DeleteModel(name='Referee',),
    ]
