# Generated by Django 3.0.4 on 2020-03-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200308_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='journey',
            field=models.IntegerField(default=0),
        ),
    ]
